# Generated by Django 4.2.4 on 2023-11-09 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('Enquiry', models.CharField(max_length=20)),
                ('Person', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=55, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('Chicken Items', 'Chicken Items'), ('Mutton Items', 'Mutton Items'), ('Fish Items', 'Fish Items'), ('Dal', 'Dal'), ('Rice', 'Rice'), ('Flourbased', 'Flourbased'), ('Veg Menu', 'Veg Menu'), ('Snacks', 'Snacks'), ('Sweets', 'Sweets'), ('Drinks', 'Drinks'), ('Salads', 'Salads'), ('Papad', 'Papad'), ('Chutney', 'Chutney')], default='Veg Menu', max_length=50)),
            ],
        ),
    ]
